List<String> imgPaths = [
  'assets/services/social-media-mangement.png',
  'assets/services/web-app-development.png',
  'assets/services/content-writting.png',
  'assets/services/brand-positioning.png',
  'assets/services/google-business.png',
  'assets/services/seo.png',
  'assets/services/ads.png',
  'assets/services/event-mangement.png',
  'assets/services/e-commerce.png',
  'assets/services/strategy.png',
  'assets/services/digital-marketing.png',
  'assets/services/data-analatics.png',
  'assets/services/market-research.png',
  'assets/services/lead-generation.png',
  'assets/services/payment-gateway.png',
  'assets/services/video-production.png',
];